__include__: [
  './rtv4_hgnetv2_s_grape_point_v4_exp3.yml'
]

output_dir: ./outputs/grape_point_v4_exp4_full_top_roi_yw

PostProcessor:
  point_decode_clamp_x_abs: 0.72
  point_decode_clamp_y_min: -0.72
  point_decode_clamp_y_max: 0.22

RTv4Criterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_has_picking: 1.2
    loss_picking_offset: 4.0
    loss_picking_locality: 0.12
  losses: ['mal', 'boxes', 'local', 'has_picking', 'picking_offset', 'picking_locality']
  point_coord_weight_x: 1.0
  point_coord_weight_y: 1.2
  point_locality_x_abs_max: 0.70
  point_locality_y_min: -0.72
  point_locality_y_max: 0.22
  point_locality_power: 2.0
