__include__: [
  '../dfine/dfine_hgnetv2_s_coco.yml',
  '../base/rtv4.yml'
]

output_dir: ./outputs/grape_point_base
print_freq: 50

sync_bn: False

num_classes: 1
remap_mscoco_category: False

evaluator:
  type: GrapePointEvaluator
  iou_types: ['bbox', ]
  point_iou_threshold: 0.5
  has_picking_threshold: 0.5

train_dataloader:
  dataset:
    type: GrapePointCocoDetection
    img_folder: ./dataset/train
    ann_file: ./dataset/train/_annotations.grape_point.json
    transforms:
      policy:
        epoch: 72
  total_batch_size: 8
  num_workers: 2
  collate_fn:
    mixup_prob: 0.0
    mixup_epochs: [0, 0]
    stop_epoch: 72

val_dataloader:
  dataset:
    type: GrapePointCocoDetection
    img_folder: ./dataset/valid
    ann_file: ./dataset/valid/_annotations.grape_point.json
  total_batch_size: 4
  num_workers: 0

DFINETransformer:
  use_picking_point_head: True

PostProcessor:
  use_picking_point: True
  has_picking_threshold: 0.5

RTv4Criterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_has_picking: 1
    loss_picking_offset: 5
  losses: ['mal', 'boxes', 'local', 'has_picking', 'picking_offset']
  gamma: 1.5

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.00005
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 100

flat_epoch: 40
no_aug_epoch: 8
