__include__: [
  '../dfine/dfine_hgnetv2_s_coco.yml',
  '../base/rtv4.yml'
]

output_dir: ./outputs/baseline_base
print_freq: 50

sync_bn: False

num_classes: 2
remap_mscoco_category: False

train_dataloader:
  dataset:
    img_folder: ./dataset/train
    ann_file: ./dataset/train/_annotations.rtv4.json
    transforms:
      policy:
        epoch: [4, 40, 72]
  total_batch_size: 8
  num_workers: 2
  collate_fn:
    mixup_epochs: [4, 40]
    stop_epoch: 72

val_dataloader:
  dataset:
    img_folder: ./dataset/valid
    ann_file: ./dataset/valid/_annotations.rtv4.json
  total_batch_size: 4
  num_workers: 0

RTv4Criterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5}
  losses: ['mal', 'boxes', 'local']
  gamma: 1.5

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.00005
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 100

flat_epoch: 40
no_aug_epoch: 8

