__include__: [
  './rtv4_hgnetv2_s_grape_point_v7_exp2.yml'
]

output_dir: ./outputs/grape_point_v7_exp2_dn_teacher_roi

DFINETransformer:
  point_teacher_roi_mode: dn_jitter
  point_teacher_roi_apply_to: dn_only
  point_teacher_roi_detach: True
