__include__: [
  './rtv4_hgnetv2_s_grape_point_v6_common.yml'
]

output_dir: ./outputs/grape_point_v6_exp2_instance_binding_relative

train_dataloader:
  dataset:
    regenerate_point_offsets: True
    point_offset_mode: bbox_relative

val_dataloader:
  dataset:
    regenerate_point_offsets: True
    point_offset_mode: bbox_relative

DFINETransformer:
  point_instance_binding_mode: query_box
  point_offset_activation: sigmoid_range
  point_offset_min: -0.20
  point_offset_max: 1.20

PostProcessor:
  use_picking_point: True
  has_picking_threshold: 0.5
  point_offset_mode: bbox_relative
