__include__: [
  './rtv4_hgnetv2_s_grape_point_v7_exp2_dn_teacher_roi.yml'
]

output_dir: ./outputs/grape_point_v7_exp2_dn_teacher_roi_light_loss

RTv4Criterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_has_picking: 1.2
    loss_picking_offset: 3.0
  losses: ['mal', 'boxes', 'local', 'has_picking', 'picking_offset']
