__include__: [
  './rtv4_hgnetv2_s_grape_point_v5_common.yml'
]

output_dir: ./outputs/grape_point_v5_exp2_geo

RTv4Criterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_has_picking: 1.2
    loss_picking_offset: 4.0
    loss_picking_geo: 0.12
  losses: ['mal', 'boxes', 'local', 'has_picking', 'picking_offset', 'picking_geo']
  top_region_ratio: 0.38
  top_margin_ratio: 0.14
  lambda_geo: 0.12
