__include__: [
  './rtv4_hgnetv2_s_grape_point_v7_exp2.yml'
]

output_dir: ./outputs/grape_point_v7_exp2_median_anchor

train_dataloader:
  dataset:
    regenerate_point_offsets: True
    point_offset_mode: top_center
    point_anchor_x_ratio: 0.5039
    point_top_anchor_ratio: 0.0384

val_dataloader:
  dataset:
    regenerate_point_offsets: True
    point_offset_mode: top_center
    point_anchor_x_ratio: 0.5039
    point_top_anchor_ratio: 0.0384

PostProcessor:
  use_picking_point: True
  has_picking_threshold: 0.5
  point_offset_mode: top_center
  point_anchor_x_ratio: 0.5039
  point_top_anchor_ratio: 0.0384
