__include__: [
  './rtv4_hgnetv2_s_grape_point_v2.yml'
]

output_dir: ./outputs/grape_point_v5_common

point_checkpointing:
  enabled: True
  grape_class_name: grape
  alpha: 0.35
  beta: 0.20
  point_error_norm_px: 40.0

RTv4Criterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_has_picking: 1.2
    loss_picking_offset: 4.0
  losses: ['mal', 'boxes', 'local', 'has_picking', 'picking_offset']
  gamma: 1.5
  point_loss_type: wing
  wing_loss_omega: 0.25
  wing_loss_epsilon: 0.05
  point_coord_weight_x: 1.0
  point_coord_weight_y: 1.0
  dense_positive_iou_thresh: 0.0
  dense_positive_topk: 0
  lambda_dense_has: 0.0
  lambda_dense_point: 0.0
  top_region_ratio: 0.35
  top_margin_ratio: 0.12
  lambda_geo: 0.0
