__include__: [
  './rtv4_hgnetv2_s_grape_point_v7_exp2.yml'
]

output_dir: ./outputs/grape_point_v7_exp2_taller_toproi

DFINETransformer:
  point_top_local_width_scale: 1.08
  point_top_local_y_min_ratio: -0.20
  point_top_local_y_max_ratio: 0.55
