__include__: [
  ./rtv4_hgnetv2_s_grape_point_enc_ema_bifpn_weighted_fusion.yml
]

output_dir: ./outputs/25_grouped_aux_control/ema_bifpn_continue20_control
epoches: 20

optimizer:
  type: AdamW
  params:
    - params: ^(?=.*backbone)(?!.*bn).*$
      lr: 0.0000125
    - params: ^(?=.*(?:norm|bn)).*$
      weight_decay: 0.0
  lr: 0.000025
  betas: [0.9, 0.999]
  weight_decay: 0.0001

DFINETransformer:
  use_grouped_picking_query: false

PostProcessor:
  use_grouped_picking_offsets: false
